### ISSUE TITLE
Add usage examples / documentation to Readme.MD

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus.Callbacks#25]
Thre Readme.MD is a little bare.  

Recommend adding links to existing documentation: 

- [Synchronous request-response (callbacks)](http://docs.particular.net/nservicebus/upgrades/5to6#synchronous-request-response-callbacks) 
- [Handling Responses on the Client Side](http://docs.particular.net/nservicebus/messaging/handling-responses-on-the-client-side)
- [Callback Sample](http://docs.particular.net/samples/callbacks/)

**Comment by timbussmann** [comment]
We usually do not provide special readmes for each repositories since this ends up in quite a lot if maintenance effort additionally to the official documentation.

We could add a simple readme as in the testing repo here: https://github.com/Particular/NServiceBus.Testing

thanks for the feedback @ppittle :+1:

**Comment by ppittle** [comment]
Adding links to the documentation works for me!

**Comment by timbussmann** [comment]
added doco/sample links to the readme on this PR: https://github.com/Particular/NServiceBus.Callbacks/pull/28
