### ISSUE TITLE
Disable Callback support

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus.Callbacks#33]
Is there a way to disable callback support?

I have need (in a testing library) to reference `NServiceBus.Callbacks` but I don't want to load it into every endpoint (specifically because of https://github.com/Particular/NServiceBus.Callbacks/issues/24).

`CallbackSupport` is private (https://github.com/Particular/NServiceBus.Callbacks/blob/develop/src/NServiceBus.Callbacks/CallbackSupport.cs#L5), so `config.DisableFeature<CallbackSupport>()` doesn't work.

Is there an alternative recommended way to disable callback support?

I can get it to work via `config.ExcludeAssemblies("NServiceBus.Callbacks.dll")` but this seems pretty hacky.

**Comment by bording** [comment]
Currently, the assumption is that if you've referenced the package, then you want to use the feature. Because of this, that's why solving #24 is something we need to address.

What scenario are you currently needing the callbacks package for in your testing library? Depending on what you're trying to do, it might be possible to remove the package and mimic some of it without it.

For example, if you just need to route reply messages back to a specific endpoint, you could specify an instance discriminator and use the `SendOptions` `RouteReplyToThisInstance` extension method.

**Comment by ppittle** [comment]
In my test project I have two the following tests:

1. Using `NServiceBus.Callbacks` to make calls an out of process Handler (in process X) and then block waiting for results.  (I need the blocking call to timeout, AFAIK I can't set a cancellation token in `SendOptions` (https://github.com/Particular/NServiceBus/issues/3785)
2. Construct the Host in Process X and instantiate each Handler to verify dependency injection bindings are bound correctly.

Because of the reference to `NServiceBus.Callbacks` test 2 fails (because of #24).  

So yes, #24 should solve my immediate problem.  However, looking at https://github.com/Particular/NServiceBus.Callbacks/blob/develop/src/NServiceBus.Callbacks/CallbackSupport.cs#L5 it appeared trivial to mark `CallbackSupport` public to support `config.DisableFeature<CallbackSupport>()`.  So I guess at this point, out of curiosity, is there a compelling reason not to support disabling features are optionally referenced as `NServiceBus.Callbacks` is?  Is this NSB standing operating procedure?

**Comment by danielmarbach** [comment]
@ppittle 

Can you elaborate your first point? I don't understand it. 

Since you can pass the cancellation token send options as shown here

http://docs.particular.net/nservicebus/messaging/handling-responses-on-the-client-side#cancellation

and when we release the next version of the callback APIs you can directly pass in the cancellation token into the request method.

https://github.com/Particular/NServiceBus.Callbacks/commit/37b6180396271eaae8c80bbae1a3103029b3b434

**Comment by dasjestyr** [comment]
I have the same problem. No reference to the callback library but it's still giving me the error

**Comment by timbussmann** [comment]
if making the feature public resolves this issue and #24 as well, this sounds like a reasonable change to me.

**Comment by danielmarbach** [comment]
For me as well. Should we proceed with this @Particular/nservicebus-maintainers ?

**Comment by andreasohlund** [comment]
I'm fine with doing this but lets add a custom `.DisableCallbacks()` method since we want to get rid of the `.DisableFeature<>` api in the future

**Comment by danielmarbach** [comment]
I'll send in a proposal that we can discuss

**Comment by andreasohlund** [comment]
Explicit

**Comment by andreasohlund** [comment]
Ugh, fatfingered the send. Should be:

Explicitly enabling FTW! :)

**Comment by dasjestyr** [comment]
Yeah, I think that would be better and more consistent with the rest of the configuration builder

**Comment by danielmarbach** [comment]
Closed via https://github.com/Particular/NServiceBus.Callbacks/pull/62
